import fs from 'node:fs'; import path from 'node:path'; import assert from 'node:assert/strict'; import { performance } from 'node:perf_hooks'; import { spawnSync } from 'node:child_process';
import { ROOT, extractOracle, PROFILES, runProfile, firstDiff, exactFingerprint, causalState, loadOracle, FIXED_DT, BROWSER_CONFIG } from './m0/lib.mjs';

const cmd=process.argv[2]??'help'; const args=process.argv.slice(3);
const evidence=path.join(ROOT,'evidence/m0'); const goldPath=path.join(evidence,'golden-fingerprints.json');
const selected=()=>args.length?PROFILES.filter(p=>args.includes(p.id)):PROFILES;
const legacyFingerprint=(legacy)=>exactFingerprint(legacy).sha256;
const compact=(full)=>({profile:full.profile,observations:full.observations.map(o=>[o.tick,o.fingerprint.sha256,legacyFingerprint(o.legacy),o.causal.simTime,o.causal.season,o.causal.nextId,o.causal.births,o.causal.deaths,o.causal.extinctions,o.causal.blobs.length,o.causal.foods.length])});

if(cmd==='source'){
  console.log(JSON.stringify(extractOracle().receipt,null,2));
}else if(cmd==='generate'){
  const current=fs.existsSync(goldPath)?JSON.parse(fs.readFileSync(goldPath,'utf8')):{format:'gloopipelago-m0-golden-fingerprints',schema:2,observationColumns:['tick','stateSha256','legacySha256','simTime','season','nextId','births','deaths','extinctions','population','food'],profiles:[],claim:'stateSha256 hashes full causal state; legacySha256 hashes historical derived snapshot.'};
  const byId=new Map(current.profiles.map(x=>[x.profile.id,x]));
  for(const p of selected()){ const out=compact(runProfile(p)); byId.set(p.id,out); console.log(`generated ${p.id} ${out.observations.at(-1)[1]}`); }
  current.profiles=[...byId.values()].sort((a,b)=>a.profile.id.localeCompare(b.profile.id)); fs.writeFileSync(goldPath,JSON.stringify(current,null,2)+'\n');
}else if(cmd==='verify'){
  const set=JSON.parse(fs.readFileSync(goldPath,'utf8')); const byId=new Map(set.profiles.map(x=>[x.profile.id,x])); const r1=extractOracle().receipt,r2=extractOracle().receipt; assert.equal(r1.sourceSha256,r2.sourceSha256);assert.equal(r1.oracleSha256,r2.oracleSha256);
  for(const p of selected()){
    const e=byId.get(p.id); assert.ok(e,`missing golden ${p.id}`); const a=runProfile(p); assert.deepEqual(a.profile,e.profile); assert.equal(a.observations.length,e.observations.length);
    for(let i=0;i<a.observations.length;i++){const x=a.observations[i],y=e.observations[i]; const [tick,stateSha,legacySha,simTime,season,nextId,births,deaths,extinctions,population,food]=y; assert.equal(x.tick,tick); assert.equal(x.fingerprint.sha256,stateSha,`${p.id} tick ${x.tick}`); assert.equal(legacyFingerprint(x.legacy),legacySha,`${p.id} legacy tick ${x.tick}`); assert.deepEqual([x.causal.simTime,x.causal.season,x.causal.nextId,x.causal.births,x.causal.deaths,x.causal.extinctions,x.causal.blobs.length,x.causal.foods.length],[simTime,season,nextId,births,deaths,extinctions,population,food]); } console.log(`PASS ${p.id}`);
  }
  const {Simulation}=loadOracle(); const a=new Simulation({seed:1,width:900,height:700,...PROFILES[0].config}),b=new Simulation({seed:1,width:900,height:700,...PROFILES[0].config}); b.blobs[17].g.diet+=.001; const d=firstDiff(causalState(a),causalState(b)); assert.equal(d.path,'blobs[17].g.diet'); assert.notEqual(exactFingerprint(causalState(a)).sha256,exactFingerprint(causalState(b)).sha256); console.log('PASS state-diff self-test');
}else if(cmd==='specimens'){
  const {Simulation}=loadOracle(); const G={hue:180,speed:.9,sense:68,size:5,eff:.96,wander:.7,diet:0};
  const blank=(seed=1,opts={})=>{const s=new Simulation({seed,width:900,height:700,...BROWSER_CONFIG,...opts});s.blobs=[];s.foods=[];s.births=0;s.deaths=0;s.extinctions=0;s.nextId=1;return s};
  const blob=(s,{x=450,y=350,energy=70,age=0,g=G,generation=0,id=null}={})=>{s.spawnBlob(x,y,{...g},generation,energy,false);const b=s.blobs.at(-1);if(id!=null)b.id=id;b.vx=0;b.vy=0;b.a=0;b.age=age;b.reproCooldown=0;return b};
  const results={format:'gloopipelago-m0-process-specimens',schema:1,specimens:{}};
  {const s=blank(7,{mutationScale:0,foodRate:0});blob(s,{energy:1000});s.step(FIXED_DT);const gens=s.blobs.map(x=>x.generation);assert.deepEqual(gens,[0,1,2,3]);assert.equal(s.births,3);results.specimens['S-LIVE-APPEND']={births:s.births,generations:gens,fingerprint:exactFingerprint(causalState(s)).sha256}}
  function contested(reverse){const s=blank(11,{mutationScale:0,foodRate:0});blob(s,{id:1});blob(s,{id:2});s.nextId=3;if(reverse)s.blobs.reverse();s.foods=[{x:450,y:350,e:10,rich:true,kind:-1,expiresAt:100}];s.step(FIXED_DT);const winner=s.blobs.slice().sort((x,y)=>x.id-y.id).map(x=>[x.id,x.energy]).sort((x,y)=>y[1]-x[1])[0][0];return{winner,state:s}}
  {const n=contested(false),r=contested(true);assert.equal(n.winner,1);assert.equal(r.winner,2);results.specimens['S-CONTENDED-FOOD']={normalWinner:n.winner,reversedWinner:r.winner,normalFingerprint:exactFingerprint(causalState(n.state)).sha256,reversedFingerprint:exactFingerprint(causalState(r.state)).sha256}}
  {const s=blank(13,{mutationScale:0,foodRate:0});for(let i=0;i<259;i++)blob(s,{x:10+(i%30)*20,y:10+Math.floor(i/30)*20,energy:i<2?200:1,id:i+1});s.nextId=260;s.step(FIXED_DT);assert.equal(s.blobs.length,260);assert.equal(s.births,1);assert.ok(s.blobs.find(x=>x.id===1).reproCooldown>0);assert.equal(s.blobs.find(x=>x.id===2).reproCooldown,0);results.specimens['S-POP-CAP']={population:s.blobs.length,births:s.births,firstCooldown:s.blobs.find(x=>x.id===1).reproCooldown,secondCooldown:s.blobs.find(x=>x.id===2).reproCooldown,fingerprint:exactFingerprint(causalState(s)).sha256}}
  {const s=blank(17,{mutationScale:0,foodRate:0});blob(s,{energy:200,age:170});s.step(FIXED_DT);assert.equal(s.births,1);assert.equal(s.deaths,1);assert.equal(s.blobs.length,1);results.specimens['S-AGE-REPRO']={births:s.births,deaths:s.deaths,survivorGenerations:s.blobs.map(x=>x.generation),fingerprint:exactFingerprint(causalState(s)).sha256}}
  {const s=blank(19,{mutationScale:0,foodRate:0});blob(s);s.foods=[{x:450,y:350,e:5,rich:true,kind:-1,expiresAt:100},{x:450,y:350,e:15,rich:true,kind:-1,expiresAt:100}];s.step(FIXED_DT);assert.deepEqual(s.foods.map(f=>f.e),[5]);results.specimens['S-FOOD-ORDER']={remainingEnergy:s.foods.map(f=>f.e),fingerprint:exactFingerprint(causalState(s)).sha256}}
  {const s=blank(23,{mutationScale:0,foodRate:0});const survivor=blob(s,{energy:70,id:1});blob(s,{energy:-1,id:2});s.nextId=3;let seq=[1,0,.5];s.rng=()=>seq.length?seq.shift():.5;s.step(FIXED_DT);const afterFirst={foods:s.foods.length,survivorEnergy:survivor.energy,deaths:s.deaths};assert.equal(afterFirst.deaths,1);assert.equal(afterFirst.foods,1);const before=survivor.energy;s.step(FIXED_DT);assert.ok(survivor.energy>before);results.specimens['S-CORPSE-PHASE']={afterFirst,afterSecond:{foods:s.foods.length,survivorEnergy:survivor.energy,deaths:s.deaths},fingerprint:exactFingerprint(causalState(s)).sha256}}
  {const s=blank(29,{mutationScale:0,foodRate:0});s.foods=Array.from({length:10},(_,i)=>({x:i,y:0,e:i+1,rich:false,kind:0,expiresAt:100}));s.blobs=[];s.catastrophe();assert.deepEqual(s.foods.map(f=>f.e),[8,9,10]);results.specimens['S-CATASTROPHE']={remaining:s.foods.map(f=>f.e),fingerprint:exactFingerprint(causalState(s)).sha256}}
  {const s=blank(31,{mutationScale:0,foodRate:0});blob(s,{energy:1e9});for(let i=0;i<2040;i++)s.step(FIXED_DT);const t=s.simTime,se=s.season;assert.equal(se,0);s.step(FIXED_DT);assert.equal(s.season,1);results.specimens['S-FLOAT-TIME']={tick2040:{simTime:t,season:se},tick2041:{simTime:s.simTime,season:s.season},fingerprint:exactFingerprint(causalState(s)).sha256}}
  {const s=blank(37,{mutationScale:0,foodRate:0,autoReseed:false});s.step(FIXED_DT);const afterFirst={population:s.blobs.length,extinctions:s.extinctions};s.step(FIXED_DT);const afterSecond={population:s.blobs.length,extinctions:s.extinctions};assert.deepEqual(afterFirst,{population:0,extinctions:1});assert.deepEqual(afterSecond,{population:0,extinctions:2});results.specimens['S-EMPTY-NORESEED']={afterFirst,afterSecond,fingerprint:exactFingerprint(causalState(s)).sha256}}
  {const s=blank(41,{mutationScale:0,foodRate:0,autoReseed:true});s.step(FIXED_DT);const afterFirst={population:s.blobs.length,extinctions:s.extinctions,nextId:s.nextId};assert.equal(afterFirst.population,12);assert.equal(afterFirst.extinctions,1);assert.equal(afterFirst.nextId,13);results.specimens['S-EMPTY-AUTORESEED']={afterFirst,generations:s.blobs.map(b=>b.generation),fingerprint:exactFingerprint(causalState(s)).sha256}}
  console.log(JSON.stringify(results,null,2));
}else if(cmd==='throughput'){
  const {Simulation}=loadOracle();const runs=[],ticks=6000;for(const seed of [1,0x12345678,0x9E3779B9,0xDEADBEEF]){const s=new Simulation({seed,width:900,height:700,...BROWSER_CONFIG});const t0=performance.now();for(let i=0;i<ticks;i++)s.step(FIXED_DT);const ms=performance.now()-t0;runs.push({seed,ticks,ms,ticksPerSecond:ticks/(ms/1000)})}const vals=runs.map(r=>r.ticksPerSecond).sort((a,b)=>a-b);console.log(JSON.stringify({format:'gloopipelago-m0-throughput-characterization',schema:1,runtime:process.version,ticksPerRun:ticks,runs,medianTicksPerSecond:(vals[1]+vals[2])/2,note:'Characterization only; not an absolute M1 pass threshold.'},null,2));
}else if(cmd==='browser-sanity'){
  const version=spawnSync('/usr/bin/chromium',['--version'],{encoding:'utf8'}).stdout.trim();const probe=spawnSync('timeout',['12s','/usr/bin/chromium','--headless','--no-sandbox','--disable-gpu','--disable-dev-shm-usage','--disable-background-networking','--disable-sync','--disable-default-apps','--disable-extensions','--no-first-run','--mute-audio','--dump-dom','data:text/html,<html><body>gloop-m0-minimal</body></html>'],{encoding:'utf8'});console.log(JSON.stringify({format:'gloopipelago-m0-browser-sanity-environment',schema:1,chromiumVersion:version,minimalProbe:{exitCode:probe.status,signal:probe.signal,outputTail:(probe.stdout+probe.stderr).slice(-4000)},status:probe.status===124?'UNAVAILABLE':probe.status===0?'PASS_MINIMAL':'FAILED_ENVIRONMENT',claim:'Browser-vs-extracted-core sanity is not qualified when the minimal browser probe is unavailable.'},null,2));
}else{
 console.log('Usage: node tools/m0.mjs <source|generate|verify|specimens|throughput|browser-sanity> [profile ids...]');
}
